const ROLES = {
  ADMIN: "ADMIN",
  PROCUREMENT: "PROCUREMENT",
  AUDITOR: "AUDITOR",
};

const ORDER_STATUS = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  APPROVED: "APPROVED",
  DELIVERED: "DELIVERED",
};

module.exports = { ROLES, ORDER_STATUS };
